# Generated by Django 5.1.3 on 2024-12-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omgg', '0002_alter_comment_author_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='address',
            new_name='title',
        ),
    ]
